/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/index.html', './src/**/*.{html,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        td: {
          brand: {
            DEFAULT: '#0052D9',
            hover: '#366EF4',
            active: '#003CAB',
          },
          danger: '#E34D59',
          success: '#00A870',
          warning: '#ED7B2F',
          text: {
            primary: '#1D2129',
            secondary: '#4E5969',
            tertiary: '#86909C',
            disabled: '#C9CDD4',
            inverse: '#FFFFFF',
          },
          border: {
            base: '#DCDCDC',
            strong: '#C9CDD4',
          },
          bg: {
            page: '#F3F5F9',
            card: '#FFFFFF',
            secondary: '#F7F8FA',
            soft: '#EEF3FF',
          },
        },
      },
      borderRadius: {
        'td-xs': '8rpx',
        'td-sm-rpx': '10rpx',
        'td-rpx': '16rpx',
        'td-lg-rpx': '20rpx',
        'td-xl-rpx': '24rpx',
        'td-2xl-rpx': '32rpx',
        'td-pill-rpx': '9999rpx',
        'td-sm': '10px',
        td: '16px',
        'td-lg': '20px',
        'td-xl': '24px',
        'td-pill': '9999px',
      },
      spacing: {
        'rpx-4': '4rpx',
        'rpx-6': '6rpx',
        'rpx-8': '8rpx',
        'rpx-10': '10rpx',
        'rpx-12': '12rpx',
        'rpx-14': '14rpx',
        'rpx-16': '16rpx',
        'rpx-20': '20rpx',
        'rpx-24': '24rpx',
        'rpx-28': '28rpx',
        'rpx-32': '32rpx',
        'rpx-36': '36rpx',
        'rpx-40': '40rpx',
        'rpx-44': '44rpx',
        'rpx-48': '48rpx',
        'rpx-52': '52rpx',
        'rpx-56': '56rpx',
        'rpx-64': '64rpx',
        'rpx-72': '72rpx',
        'rpx-80': '80rpx',
        'rpx-88': '88rpx',
        'rpx-96': '96rpx',
        'rpx-112': '112rpx',
        'rpx-128': '128rpx',
        'rpx-160': '160rpx',
        'rpx-196': '196rpx',
      },
      fontSize: {
        'rpx-20': '20rpx',
        'rpx-22': '22rpx',
        'rpx-24': '24rpx',
        'rpx-26': '26rpx',
        'rpx-28': '28rpx',
        'rpx-30': '30rpx',
        'rpx-32': '32rpx',
        'rpx-36': '36rpx',
        'rpx-40': '40rpx',
        'rpx-44': '44rpx',
        'rpx-48': '48rpx',
      },
      boxShadow: {
        'td-sm': '0 2px 10px rgba(17, 24, 39, 0.06)',
        td: '0 8px 24px rgba(17, 24, 39, 0.10)',
        'td-lg': '0 16px 36px rgba(17, 24, 39, 0.14)',
      },
      animation: {
        'fade-in': 'fade-in .3s ease both',
        'fade-in-up': 'fade-in-up .35s ease both',
        'scale-in': 'scale-in .25s ease both',
        blink: 'blink 1s step-start infinite',
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in-up': {
          from: { opacity: '0', transform: 'translateY(20px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.8)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        blink: {
          '0%, 50%': { opacity: '1' },
          '51%, 100%': { opacity: '0' },
        },
      },
    },
  },
}
