/* eslint-disable */
/* prettier-ignore-start */
/**
 * Auto-generated by frontend/scripts/generate-api.mjs
 * Do not edit this file directly.
 */

import { BaseApiClient, StreamHandlers, StreamRequestHandle } from "./request";

export type ChatCompletionsDto = {
  modelId?: string;
  provider?: string;
  platform?: string;
  model?: string;
  temperature?: number;
  maxOutputTokens?: number;
  topP?: number;
  conversationId?: string;
  content: string;
};

export type CreateConversationDto = {
  title?: string;
};

export type ImageGenerationDto = {
  conversationId: string;
  prompt: string;
};

export type PhoneLoginDto = {
  phone: string;
  code: string;
};

export type RefreshTokenDto = {
  refreshToken: string;
};

export type ResumeSseDto = {
  lastEventId?: number;
};

export type SendCodeDto = {
  phone: string;
};

export type UpdateProfileDto = {
  nickname?: string;
  avatarUrl?: string;
};

export type VoiceCompletionsDto = {
  modelId?: string;
  provider?: string;
  platform?: string;
  model?: string;
  temperature?: number;
  maxOutputTokens?: number;
  topP?: number;
  conversationId?: string;
};

export type WechatLoginDto = {
  code: string;
};

export class Api extends BaseApiClient {

  /**
   * 登出
   */
  logout(): Promise<unknown> {
    return this.request<unknown>({
      url: "/auth/logout",
      method: "POST"
    });
  }


  /**
   * 手机号登录
   */
  phoneLogin(body: PhoneLoginDto): Promise<unknown> {
    return this.request<unknown, PhoneLoginDto>({
      url: "/auth/phone/login",
      method: "POST",
      data: body
    });
  }


  /**
   * 发送手机验证码
   */
  sendCode(body: SendCodeDto): Promise<unknown> {
    return this.request<unknown, SendCodeDto>({
      url: "/auth/phone/send-code",
      method: "POST",
      data: body
    });
  }


  /**
   * 刷新令牌
   */
  refresh(body: RefreshTokenDto): Promise<unknown> {
    return this.request<unknown, RefreshTokenDto>({
      url: "/auth/refresh",
      method: "POST",
      data: body
    });
  }


  /**
   * 微信登录
   */
  wechatLogin(body: WechatLoginDto): Promise<unknown> {
    return this.request<unknown, WechatLoginDto>({
      url: "/auth/wechat-login",
      method: "POST",
      data: body
    });
  }


  /**
   * AI 图片生成
   */
  imageGenerations(body: ImageGenerationDto): Promise<unknown> {
    return this.request<unknown, ImageGenerationDto>({
      url: "/chat/image-generations",
      method: "POST",
      data: body
    });
  }


  /**
   * 发送文本消息并开始流式回复
   */
  sendMessage(body: ChatCompletionsDto, handlers: StreamHandlers<unknown> = {}): StreamRequestHandle {
    return this.stream<unknown, ChatCompletionsDto>({
      url: "/chat/message",
      method: "POST",
      data: body
    }, handlers);
  }


  /**
   * 发送语音消息
   */
  voiceCompletions(args: {
    body?: VoiceCompletionsDto;
    filePath: string;
    fileFieldName?: string;
  }): Promise<unknown> {
    return this.upload<unknown, VoiceCompletionsDto>({
      url: "/chat/voice-messages",
      method: "POST",
      filePath: args.filePath,
      name: args.fileFieldName || "file",
      formData: args.body
    });
  }


  /**
   * 获取所有会话
   */
  findAll(): Promise<unknown> {
    return this.request<unknown>({
      url: "/conversations",
      method: "GET"
    });
  }


  /**
   * 创建新会话
   */
  create(body: CreateConversationDto): Promise<unknown> {
    return this.request<unknown, CreateConversationDto>({
      url: "/conversations",
      method: "POST",
      data: body
    });
  }


  /**
   * 删除会话
   */
  delete(args: {
    id: string;
  }): Promise<unknown> {
    return this.request<unknown>({
      url: "/conversations/{id}",
      method: "DELETE",
      pathParams: {
            id: args.id
          }
    });
  }


  /**
   * 健康检查
   */
  check(): Promise<{
  status?: string;
  info?: {
    [key: string]: {
      status: string;
      [key: string]: unknown;
    };
  } | null;
  error?: {
    [key: string]: {
      status: string;
      [key: string]: unknown;
    };
  } | null;
  details?: {
    [key: string]: {
      status: string;
      [key: string]: unknown;
    };
  };
}> {
    return this.request<{
  status?: string;
  info?: {
    [key: string]: {
      status: string;
      [key: string]: unknown;
    };
  } | null;
  error?: {
    [key: string]: {
      status: string;
      [key: string]: unknown;
    };
  } | null;
  details?: {
    [key: string]: {
      status: string;
      [key: string]: unknown;
    };
  };
}>({
      url: "/health",
      method: "GET"
    });
  }


  /**
   * 查询 SSE 任务状态
   */
  getTask(args: {
    taskId: string;
  }): Promise<unknown> {
    return this.request<unknown>({
      url: "/sse-tasks/{taskId}",
      method: "GET",
      pathParams: {
            taskId: args.taskId
          }
    });
  }


  /**
   * 取消 SSE 任务
   */
  cancelTask(args: {
    taskId: string;
  }): Promise<unknown> {
    return this.request<unknown>({
      url: "/sse-tasks/{taskId}/cancel",
      method: "POST",
      pathParams: {
            taskId: args.taskId
          }
    });
  }


  /**
   * 微信小程序/通用客户端恢复 SSE
   */
  resumeTask(args: {
    taskId: string;
    body: ResumeSseDto;
  }, handlers: StreamHandlers<unknown> = {}): StreamRequestHandle {
    return this.stream<unknown, ResumeSseDto>({
      url: "/sse-tasks/{taskId}/resume",
      method: "POST",
      pathParams: {
            taskId: args.taskId
          },
      data: args.body
    }, handlers);
  }


  /**
   * 浏览器 SSE 建链/恢复
   */
  streamTask(args: {
    taskId: string;
    cursor: number;
  }, handlers: StreamHandlers<unknown> = {}): StreamRequestHandle {
    return this.stream<unknown>({
      url: "/sse-tasks/{taskId}/stream",
      method: "GET",
      pathParams: {
            taskId: args.taskId
          },
      query: {
            cursor: args.cursor
          }
    }, handlers);
  }


  /**
   * 获取当前用户信息
   */
  getProfile(): Promise<unknown> {
    return this.request<unknown>({
      url: "/user/profile",
      method: "GET"
    });
  }


  /**
   * 更新用户资料
   */
  updateProfile(body: UpdateProfileDto): Promise<unknown> {
    return this.request<unknown, UpdateProfileDto>({
      url: "/user/profile",
      method: "PATCH",
      data: body
    });
  }

}

export const api = new Api();

export default api;
/* prettier-ignore-end */
