export const CHAT_CONTEXT_RECENT_MESSAGE_LIMIT = 12;
export const CONVERSATION_SUMMARY_MIN_SOURCE_MESSAGE_COUNT = 4;
export const CONVERSATION_SUMMARY_MAX_SOURCE_MESSAGE_COUNT = 80;
export const CONVERSATION_SUMMARY_MAX_OUTPUT_TOKENS = 500;
export const CONVERSATION_SUMMARY_TEMPERATURE = 0.2;
