import type { ThemeDefinition } from "../types.js";

/** 现代像素 / 新拟态：高饱和彩 + 零圆角 + 3px 黑边 + 硬投影（浅底，仅 admin） */
export const pixelNeoTheme = {
  id: "pixel-neo",
  name: "像素·新拟态",
  shortName: "PN",
  description: "高饱和彩色 + 零圆角 + 硬投影，像素辨识度高又保可读。",
  colorScheme: "light",
  tokens: {
    pageBackground: "#f4f1e8",
    background: "#f4f1e8",
    surface: "#ffffff",
    surfaceRaised: "#ffffff",
    surfaceMuted: "#efeadd",
    surfaceHover: "#e7e0cf",
    textPrimary: "#1a1a2e",
    textSecondary: "#4a4a63",
    textMuted: "#6b6b7b",
    line: "#1a1a2e",
    lineStrong: "#1a1a2e",
    accent: "#ff5277",
    accentStrong: "#e03a5f",
    accentSoft: "#ffe0e8",
    accentInk: "#1a1a2e",
    accentSurface: "#ff5277",
    onAccent: "#ffffff",
    success: "#3bb273",
    successSoft: "#dff5e8",
    info: "#4d9de0",
    infoSoft: "#e0eefb",
    warning: "#e1a730",
    warningSoft: "#fbefd5",
    danger: "#ff5277",
    dangerSoft: "#ffe0e8",
    shadowCard: "5px 5px 0 #1a1a2e",
    shadowFloat: "8px 8px 0 #1a1a2e",
    radiusXs: "0",
    radiusSm: "0",
    radiusMd: "0",
  },
  swatches: ["#ff5277", "#4d9de0", "#3bb273"],
} as const satisfies ThemeDefinition;
